const STORAGE_KEY = "creatoreSquadrePersone.v1";
const PRESENT_STORAGE_KEY = "creatoreSquadrePresentiOggi.v1";
const DAILY_LEADERS_STORAGE_KEY = "creatoreSquadreLeaderOggi.v1";
const DRAW_INTERVAL_MS = 135;

const periodLabels = {
  under5: "Meno di 5 anni",
  fiveToTen: "5-10 anni",
  overTen: "10+ anni",
};

const periodScores = {
  under5: 0,
  fiveToTen: 1,
  overTen: 2,
};

const languageLabels = {
  chinese: "Cinese",
  italian: "Solo italiano",
  bilingual: "Bilingue",
};

const teamLanguageLabels = {
  chinese: "Cinese",
  italian: "Italiana",
};

const importHeaders = ["Nome", "Cognome/Nickname", "Data di nascita", "Lingua", "Periodo in chiesa", "Battezzato", "Leader", "Note"];

const examplePeople = [
  {
    nome: "Marco",
    nickname: "Rossi",
    birthDate: "1998-07-04",
    language: "chinese",
    churchPeriod: "overTen",
    baptized: true,
    leaderCandidate: true,
    notes: "",
  },
  {
    nome: "Sara",
    nickname: "S.",
    birthDate: "2002-07-08",
    language: "italian",
    churchPeriod: "fiveToTen",
    baptized: true,
    leaderCandidate: true,
    notes: "",
  },
  {
    nome: "Luca",
    nickname: "",
    birthDate: "2007-03-11",
    language: "bilingual",
    churchPeriod: "under5",
    baptized: false,
    leaderCandidate: false,
    notes: "",
  },
  {
    nome: "Anna",
    nickname: "Bianchi",
    birthDate: "1995-07-02",
    language: "chinese",
    churchPeriod: "overTen",
    baptized: true,
    leaderCandidate: true,
    notes: "",
  },
  {
    nome: "Davide",
    nickname: "",
    birthDate: "2004-11-20",
    language: "italian",
    churchPeriod: "fiveToTen",
    baptized: false,
    leaderCandidate: false,
    notes: "",
  },
  {
    nome: "Miriam",
    nickname: "M.",
    birthDate: "1998-01-14",
    language: "bilingual",
    churchPeriod: "fiveToTen",
    baptized: true,
    leaderCandidate: true,
    notes: "",
  },
  {
    nome: "Gioele",
    nickname: "",
    birthDate: "2008-09-05",
    language: "chinese",
    churchPeriod: "under5",
    baptized: true,
    leaderCandidate: false,
    notes: "",
  },
  {
    nome: "Noemi",
    nickname: "",
    birthDate: "2005-05-22",
    language: "chinese",
    churchPeriod: "under5",
    baptized: false,
    leaderCandidate: false,
    notes: "",
  },
];

const state = {
  people: [],
  presentIds: new Set(),
  dailyLeaderIds: new Set(),
  editingId: null,
  timer: null,
  currentTeams: [],
  drawCount: 0,
  overlayOpen: false,
  databaseSearch: "",
  databaseSelectedIds: new Set(),
  attendanceSearch: "",
  languageBalance: false,
};

const els = {
  form: document.querySelector("#personForm"),
  firstName: document.querySelector("#firstName"),
  nickname: document.querySelector("#nickname"),
  birthDate: document.querySelector("#birthDate"),
  language: document.querySelector("#language"),
  churchPeriod: document.querySelector("#churchPeriod"),
  notes: document.querySelector("#notes"),
  scorePreview: document.querySelector("#scorePreview"),
  submitPerson: document.querySelector("#submitPerson"),
  cancelEdit: document.querySelector("#cancelEdit"),
  peopleRows: document.querySelector("#peopleRows"),
  emptyPeople: document.querySelector("#emptyPeople"),
  databaseSearch: document.querySelector("#databaseSearch"),
  selectVisibleDatabase: document.querySelector("#selectVisibleDatabase"),
  clearDatabaseSelection: document.querySelector("#clearDatabaseSelection"),
  deleteSelectedPeople: document.querySelector("#deleteSelectedPeople"),
  databaseSelectedCount: document.querySelector("#databaseSelectedCount"),
  totalPeople: document.querySelector("#totalPeople"),
  totalLeaders: document.querySelector("#totalLeaders"),
  selectedTodaySummary: document.querySelector("#selectedTodaySummary"),
  saveStatus: document.querySelector("#saveStatus"),
  tabButtons: document.querySelectorAll(".tab-button"),
  databaseView: document.querySelector("#databaseView"),
  createView: document.querySelector("#createView"),
  attendanceList: document.querySelector("#attendanceList"),
  emptyAttendance: document.querySelector("#emptyAttendance"),
  attendanceSearch: document.querySelector("#attendanceSearch"),
  selectAllToday: document.querySelector("#selectAllToday"),
  clearToday: document.querySelector("#clearToday"),
  selectedPeopleCount: document.querySelector("#selectedPeopleCount"),
  selectedLeadersCount: document.querySelector("#selectedLeadersCount"),
  selectedScoreTotal: document.querySelector("#selectedScoreTotal"),
  teamCount: document.querySelector("#teamCount"),
  generationStatus: document.querySelector("#generationStatus"),
  startDraw: document.querySelector("#startDraw"),
  stopDraw: document.querySelector("#stopDraw"),
  generateOnce: document.querySelector("#generateOnce"),
  languageBalanceToggle: document.querySelector("#languageBalanceToggle"),
  teamsGrid: document.querySelector("#teamsGrid"),
  resultMeta: document.querySelector("#resultMeta"),
  runState: document.querySelector("#runState"),
  neededLeaders: document.querySelector("#neededLeaders"),
  scoreGap: document.querySelector("#scoreGap"),
  sizeGap: document.querySelector("#sizeGap"),
  loadExamples: document.querySelector("#loadExamples"),
  clearPeople: document.querySelector("#clearPeople"),
  downloadTemplate: document.querySelector("#downloadTemplate"),
  exportData: document.querySelector("#exportData"),
  importData: document.querySelector("#importData"),
  importFile: document.querySelector("#importFile"),
  drawOverlay: document.querySelector("#drawOverlay"),
  overlayTeamsGrid: document.querySelector("#overlayTeamsGrid"),
  overlayStop: document.querySelector("#overlayStop"),
  closeOverlay: document.querySelector("#closeOverlay"),
  overlayTitle: document.querySelector("#overlayTitle"),
  drawCounter: document.querySelector("#drawCounter"),
  birthdayBanner: document.querySelector("#birthdayBanner"),
  birthdayBannerNames: document.querySelector("#birthdayBannerNames"),
  birthdayOverlay: document.querySelector("#birthdayOverlay"),
  closeBirthdayOverlay: document.querySelector("#closeBirthdayOverlay"),
  birthdayWindowText: document.querySelector("#birthdayWindowText"),
  birthdayPeople: document.querySelector("#birthdayPeople"),
  toast: document.querySelector("#toast"),
};
